In [ ]:
import tensorflow as tf
from tensorflow import keras
# Helper libraries
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
pip install tensorflow

In [1]:
import tensorflow.keras
from tensorflow.keras.models import Sequential,Model
from tensorflow.keras.layers import Dense, Dropout, Flatten, Input
from tensorflow.keras.layers import Conv2D, MaxPooling2D

In [2]:
import numpy as np # numpy array and performing algebraic operations
import pandas as pd 
new_data = pd.read_csv('C:/Users/win/Downloads/new_data (1).csv')
new_data

,PLANT_ID_x,SOURCE_KEY_x,DC_POWER,AC_POWER,DAILY_YIELD,TOTAL_YIELD,AMBIENT_TEMPERATURE,MODULE_TEMPERATURE,IRRADIATION,TIME,DATE,Target
0,4135001,1BY6WEcLGh8j5v7,0.0,0.0,0.000,6259559.0,25.184316,22.857507,0.0,0:00:00,15/05/2020,0
1,4135001,1IF53ai7Xc0U56Y,0.0,0.0,0.000,6183645.0,25.184316,22.857507,0.0,0:00:00,15/05/2020,0
2,4135001,3PZuoBAID5Wc2HD,0.0,0.0,0.000,6987759.0,25.184316,22.857507,0.0,0:00:00,15/05/2020,0
3,4135001,7JYdWkrLSPkdwr4,0.0,0.0,0.000,7602960.0,25.184316,22.857507,0.0,0:00:00,15/05/2020,0
4,4135001,McdE0feGgRqW7Ca,0.0,0.0,0.000,7158964.0,25.184316,22.857507,0.0,0:00:00,15/05/2020,0
...,...,...,...,...,...,...,...,...,...,...,...,...
45675,4135001,uHbuxQJl8lW7ozc,0.0,0.0,5967.000,7287002.0,21.909288,20.427972,0.0,23:45:00,17/06/2020,0
45676,4135001,wCURE6d3bPkepu2,0.0,0.0,5147.625,7028601.0,21.909288,20.427972,0.0,23:45:00,17/06/2020,0
45677,4135001,z9Y9gH1T5YWrNuG,0.0,0.0,5819.000,7251204.0,21.909288,20.427972,0.0,23:45:00,17/06/2020,0
45678,4135001,zBIq5rxdHJRwDNY,0.0,0.0,5817.000,6583369.0,21.909288,20.427972,0.0,23:45:00,17/06/2020,0
45679,4135001,zVJPv84UY57bAof,0.0,0.0,5910.000,7363272.0,21.909288,20.427972,0.0,23:45:00,17/06/2020,0

In [3]:
X = new_data[['DC_POWER', 'AC_POWER', 'DAILY_YIELD',
       'TOTAL_YIELD', 'AMBIENT_TEMPERATURE', 'MODULE_TEMPERATURE',
       'IRRADIATION']]
y = new_data[['Target']]

In [4]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size = 0.33, random_state=7)

In [5]:
 print(X_test.shape)
X_train.shape

(15075, 7)

(30605, 7)

In [6]:
np.reshape(X_train,(-1, 7))

,DC_POWER,AC_POWER,DAILY_YIELD,TOTAL_YIELD,AMBIENT_TEMPERATURE,MODULE_TEMPERATURE,IRRADIATION
17345,0.000000,0.000000,0.000000,7072762.000,24.612695,22.749561,0.000000
21202,0.000000,0.000000,8869.000000,7260130.000,22.546733,21.027425,0.000000
22620,3427.285714,336.685714,6282.428571,6342490.429,32.281588,41.693659,0.327377
20181,12077.714290,1177.585714,3334.142857,7678575.143,30.986580,60.130983,0.928845
16316,7757.000000,759.357143,6835.857143,7051451.857,32.745856,51.327438,0.545488
...,...,...,...,...,...,...,...
34140,7884.375000,770.050000,3101.125000,7182378.125,29.662364,49.187315,0.442448
13927,4208.500000,413.250000,768.000000,7161167.000,25.312744,32.380375,0.267094
919,7707.571429,753.671429,1766.000000,7113259.000,29.351443,49.249723,0.455148
38467,9930.714286,971.014286,4655.000000,7825507.000,26.630188,45.965584,0.727764
10742,2684.250000,263.350000,129.125000,7020641.125,22.936332,23.896433,0.198913

In [7]:
batch_size = 32
epochs = 10
num_classes = 10

In [8]:
model = Sequential()

In [9]:
# Add the first layer = conv -> relu -> max pooling
model.add(Conv2D(32, kernel_size=(3, 3),
 activation='relu',
 input_shape=(28, 28, 1)))
model.add(MaxPooling2D((2, 2)))

In [10]:
# Add the second layer = conv -> relu -> max pooling
model.add(Conv2D(64,
 kernel_size=(3, 3),
 activation='relu'))

In [11]:
model.add(MaxPooling2D(pool_size=(2, 2)))
# Add the third layer = conv -> relu
model.add(Conv2D(128, (3, 3), activation='relu'))

In [12]:
# Add a fully connect layer
model.add(Flatten())
model.add(Dense(128, activation='relu'))

In [13]:
# Add a softmax to have an output with 10 classes
model.add(Dense(num_classes, activation='softmax'))

In [14]:
model.compile(
 loss = 'SparseCategoricalCrossentropy',
 #loss='categorical_crossentropy',
 optimizer='adam',
 metrics=['accuracy'])

In [15]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 conv2d (Conv2D)             (None, 26, 26, 32)        320

 max_pooling2d (MaxPooling2D  (None, 13, 13, 32)       0
 )

 conv2d_1 (Conv2D)           (None, 11, 11, 64)        18496

 max_pooling2d_1 (MaxPooling  (None, 5, 5, 64)         0
 2D)

 conv2d_2 (Conv2D)           (None, 3, 3, 128)         73856

 flatten (Flatten)           (None, 1152)              0

 dense (Dense)               (None, 128)               147584

 dense_1 (Dense)             (None, 10)                1290

=================================================================
Total params: 241,546
Trainable params: 241,546
Non-trainable params: 0
_________________________________________________________________

In [16]:
history = model.fit(X_train, y_train,
 batch_size=batch_size,
 epochs=epochs,
 verbose=1,
 validation_data=(X_test, y_test))

Epoch 1/10

ValueError: in user code:

    File "C:\Users\win\anaconda3\lib\site-packages\keras\engine\training.py", line 1160, in train_function  *
        return step_function(self, iterator)
    File "C:\Users\win\anaconda3\lib\site-packages\keras\engine\training.py", line 1146, in step_function  **
        outputs = model.distribute_strategy.run(run_step, args=(data,))
    File "C:\Users\win\anaconda3\lib\site-packages\keras\engine\training.py", line 1135, in run_step  **
        outputs = model.train_step(data)
    File "C:\Users\win\anaconda3\lib\site-packages\keras\engine\training.py", line 993, in train_step
        y_pred = self(x, training=True)
    File "C:\Users\win\anaconda3\lib\site-packages\keras\utils\traceback_utils.py", line 70, in error_handler
        raise e.with_traceback(filtered_tb) from None
    File "C:\Users\win\anaconda3\lib\site-packages\keras\engine\input_spec.py", line 295, in assert_input_compatibility
        raise ValueError(

    ValueError: Input 0 of layer "sequential" is incompatible with the layer: expected shape=(None, 28, 28, 1), found shape=(None, 7)

In [ ]:

plt.plot(history.history['accuracy'])
plt.plot(history.history['val_accuracy'])
plt.title('model accuracy')
plt.ylabel('accuracy')
plt.xlabel('epoch')
plt.legend(['train', 'test'], loc='upper left')
plt.show()

In [ ]:
plt.plot(history.history['loss'])
plt.plot(history.history['val_loss'])
plt.title('model loss')
plt.ylabel('loss')
plt.xlabel('epoch')
plt.legend(['train', 'test'], loc='upper left')
plt.show()

In [ ]:
train_score = model.evaluate(X_train_sc,
                       y_train,
                       verbose=1)
test_score = model.evaluate(X_test_sc,
                       y_test,
                       verbose=1)
labels = model.metrics_names
print('')
print(f'Training Accuracy: {train_score[1]}')
print(f'Testing Accuracy: {test_score[1]}')